/**
 * ODIPA Volunteer Prep Sheet, template + renderer
 *
 * The sheet is two-thirds static org knowledge (call flow, honest-scale
 * script, work-authorization gate, do/don'ts) rendered verbatim from this
 * file, and one-third applicant-specific content generated by the model
 * under a strict JSON contract. Static sections are never model-generated,
 * so the legally sensitive language cannot drift or hallucinate.
 *
 * House style rule: no em or en dashes anywhere, generated text is
 * sanitized on the way in.
 */

const ORG_CONTEXT = `ODIPA is a small California 501(c)(3) digital privacy nonprofit. It is founder-led and early stage. Most operations are currently the founder. Volunteer work ships and is visible, there is no committee or design team.

Publicly listed volunteer roles: Community Advocate, Content Writer, Educator/Trainer.

Real current needs a volunteer could serve:
- Educational materials, translating privacy concepts into one-pagers, infographics, and visuals
- Newsletter and social media visuals, a consistent visual identity for outreach
- Site UX review of odipa.org from a visitor's perspective
- UX or user research on how real people understand privacy and consent language, which can feed ODIPA's research publication track
- Community outreach and educational content writing
- Certification program development support

First projects must be small, self-contained, shippable in weeks by one person, and produce something public the volunteer can point to. Portfolio value is often the volunteer's real compensation.`

const PROMPT_SYSTEM = `You prepare intro-call notes about a volunteer applicant for the founder of ODIPA. You write the applicant-specific sections only. Fixed org policy sections are appended separately and are not your job.

Reply ONLY with JSON, no fences, in exactly this shape:
{
  "read": ["3 to 5 short bullets on who this applicant is, drawn only from their message"],
  "fit": [{"need": "an ODIPA need from the provided org context", "fit": "why this applicant fits it, grounded in what they stated", "value": "what the applicant gets out of it"}],
  "projects": ["first project candidate 1", "first project candidate 2"],
  "questions": [{"label": "2 to 4 word theme", "text": "the question, phrased to be spoken"}]
}

Hard rules:
- Ground every claim in what the applicant actually wrote. One stated skill is one stated skill, never inflate it into expertise.
- Map only to needs in the provided org context. Never invent programs, teams, team leads, review structures, or roles.
- 2 to 4 fit rows. Exactly 2 project candidates, each small, self-contained, shippable in weeks by one person. 3 or 4 questions.
- Never speculate about the applicant's immigration status, visa, nationality, ethnicity, gender, or age. Work authorization is handled by a fixed section that is not yours.
- Plain warm language, no marketing tone, no em dashes, no colons inside sentences.`

function esc(s) {
  return String(s || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function noDashes(s) {
  return String(s || '').replace(/\s*[\u2014\u2013]\s*/g, ', ')
}

function clean(s, max) {
  return esc(noDashes(s).trim().slice(0, max || 400))
}

/** Validate + trim the model's JSON into a safe shape, or throw. */
function normalizeGenerated(g) {
  if (!g || !Array.isArray(g.read) || !Array.isArray(g.fit) || !Array.isArray(g.projects) || !Array.isArray(g.questions))
    throw new Error('Generated JSON missing required sections')
  const read = g.read.slice(0, 5).map(x => clean(x, 300)).filter(Boolean)
  const fit = g.fit.slice(0, 4).map(r => ({
    need: clean(r && r.need, 160), fit: clean(r && r.fit, 300), value: clean(r && r.value, 200),
  })).filter(r => r.need && r.fit)
  const projects = g.projects.slice(0, 2).map(x => clean(x, 300)).filter(Boolean)
  const questions = g.questions.slice(0, 4).map(q => ({
    label: clean(q && q.label, 40), text: clean(q && q.text, 400),
  })).filter(q => q.text)
  if (!read.length || !fit.length || projects.length < 2 || !questions.length)
    throw new Error('Generated JSON sections empty after validation')
  return { read, fit, projects, questions }
}

function renderPrepSheet(inq, gen) {
  const received = inq.receivedAt
    ? new Date(Number(inq.receivedAt)).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
    : ''
  const name = clean(inq.name, 120) || 'Applicant'
  const org = clean(inq.organization, 160)

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${name} \u00b7 ODIPA Volunteer Intro Call Prep</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1F3050; background: #FFFFFF; font-size: 13px; line-height: 1.45; padding: 24px 28px; max-width: 980px; margin: 0 auto; }
  h1 { font-size: 21px; color: #1F3864; border-bottom: 3px solid #C9A227; padding-bottom: 6px; margin-bottom: 4px; }
  .sub { color: #44546A; font-size: 12px; margin-bottom: 16px; }
  h2 { font-size: 15px; color: #1F3864; margin: 18px 0 8px; border-left: 4px solid #C9A227; padding-left: 8px; }
  p { margin-bottom: 8px; }
  .say { background: #F4F6FA; border-left: 3px solid #1F3864; padding: 8px 12px; margin: 8px 0; border-radius: 0 6px 6px 0; }
  .say .lbl { display: block; font-size: 10px; font-weight: bold; color: #C9A227; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 3px; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0; }
  th { background: #1F3864; color: #FFF; text-align: left; padding: 6px 9px; font-size: 12px; }
  td { border: 1px solid #D5DAE3; padding: 6px 9px; vertical-align: top; font-size: 12.5px; }
  tr:nth-child(even) td { background: #F8F9FB; }
  .warn { background: #FDF3F3; border-left: 3px solid #B14D4D; padding: 8px 12px; margin: 8px 0; border-radius: 0 6px 6px 0; }
  .good { background: #F2F8F2; border-left: 3px solid #4D8B4D; padding: 8px 12px; margin: 8px 0; border-radius: 0 6px 6px 0; }
  ul, ol { margin: 6px 0 10px 22px; }
  li { margin-bottom: 4px; }
  .cols { display: flex; gap: 18px; }
  .col { flex: 1; }
  .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #D5DAE3; color: #667; font-size: 11px; }
  @media print { body { padding: 10px; font-size: 11.5px; } .cols { display: block; } }
</style>
</head>
<body>

<h1>${name} Intro Call, Thirty Minutes</h1>
<p class="sub">Applied ${received} via contact form \u00b7 ${clean(inq.email, 160)}${org ? ` \u00b7 ${org}` : ''} \u00b7 Volunteering inquiry</p>

<h2>Who they are, from their message</h2>
<ul>
${gen.read.map(b => `  <li>${b}</li>`).join('\n')}
</ul>

<h2>Where they fit</h2>
<table>
  <tr><th>ODIPA need</th><th>Their fit</th><th>What they get</th></tr>
${gen.fit.map(r => `  <tr><td>${r.need}</td><td>${r.fit}</td><td>${r.value}</td></tr>`).join('\n')}
</table>

<h2>First project candidates, let them choose</h2>
<ol>
${gen.projects.map(p => `  <li>${p}</li>`).join('\n')}
</ol>

<h2>Call flow, thirty minutes</h2>
<table>
  <tr><th>Min</th><th>Beat</th><th>Move</th></tr>
  <tr><td>0-5</td><td>Open</td><td>Thank them for applying, ODIPA's mission and current programs in two minutes, honest scale of the org</td></tr>
  <tr><td>5-15</td><td>Them</td><td>Their background, what they want out of volunteering, hours they realistically have, the questions below</td></tr>
  <tr><td>15-25</td><td>Fit</td><td>Walk the fit table together, converge on one first project, let them pick between the two candidates</td></tr>
  <tr><td>25-30</td><td>Close</td><td>Concrete next step with a date, the compliance items below, how they prefer to work, async or calls</td></tr>
</table>

<h2>Questions to ask</h2>
${gen.questions.map(q => `<div class="say"><span class="lbl">${q.label || 'Question'}</span>\n${q.text}</div>`).join('\n')}

<h2>Be honest about scale, same rule as every volunteer call</h2>
<div class="say"><span class="lbl">The org, said plainly</span>
"I want to be straight with you about where ODIPA is. It's early, I'm the founder and right now most of the operation is me, which means two things for you. Your work would ship and be visible, not sit in a queue behind a committee. And you'd be helping build the thing, not slotting into it. Some people find that exciting, some want more structure, both are legitimate, so tell me which you are."</div>

<h2>Compliance gate, before any work starts, ask everyone the same way</h2>
<div class="warn">
<p><strong>Work authorization check, routine for every volunteer.</strong> Asked identically of every applicant, never assumed from anything about them.</p>
<ul>
  <li><strong>US citizen or permanent resident.</strong> No gate, standard volunteer paperwork only.</li>
  <li><strong>Regular OPT (F-1).</strong> Unpaid nonprofit volunteering is permissible when the work relates to their field of study, with the EAD verified and their DSO updating SEVIS before work begins. Use the ODIPA OPT Volunteer Agreement.</li>
  <li><strong>STEM OPT extension.</strong> Unpaid volunteering is prohibited, full stop. If they are on STEM OPT, the honest answer is that ODIPA cannot take them as a volunteer right now, and pretending otherwise puts their status at risk.</li>
</ul>
<p>The way to raise it, "One routine thing I ask everyone, is there anything about your work authorization I should know for volunteer compliance? For anyone on OPT there's a specific process we follow to protect your status."</p>
</div>

<h2>Do and do not</h2>
<div class="cols">
<div class="col">
<div class="good">
<p><strong>Do</strong></p>
<ul>
  <li>Credit the quality of their application out loud where it's earned</li>
  <li>Let them choose the first project between the two candidates</li>
  <li>Name what they get out of it explicitly, it is their compensation</li>
  <li>Agree a concrete next step with a date before hanging up</li>
  <li>Mention the volunteer agreement and conflict form as routine paperwork</li>
</ul>
</div>
</div>
<div class="col">
<div class="warn">
<p><strong>Do not</strong></p>
<ul>
  <li>Claim a team, a team lead, or review structure that does not exist</li>
  <li>Promise repo or system access on day one, start with self-contained artifacts</li>
  <li>Commit to a role title or scope beyond the first project</li>
  <li>Let any work start before the authorization check clears</li>
  <li>Oversell, they applied, the job is fit-finding, not convincing</li>
</ul>
</div>
</div>
</div>

<h2>After the call, same day</h2>
<ul>
  <li>Short email, thank them, restate the agreed first project and date, attach the volunteer agreement, and if OPT applies, the OPT agreement and the EAD/SEVIS steps stated plainly</li>
  <li>Calendar hold for whatever next step was agreed</li>
</ul>

<div class="footer">ODIPA \u00b7 Volunteer intro call prep, generated ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} \u00b7 Applicant-specific sections AI-generated and human-reviewed, policy sections fixed</div>

</body>
</html>`
}

module.exports = { ORG_CONTEXT, PROMPT_SYSTEM, normalizeGenerated, renderPrepSheet }
